### ISSUE TITLE
Read/Write Exception Issue

### ISSUE THREAD

**Issue by quixoten** [wallyqs/pure-ruby-nats#6]
If a Ruby platform supports `IO::WaitReadable` and `IO::WaitWritable`, those should be the only exceptions rescued. This is because ruby extends the original error (could be either `Errno::EWOULDBLOCK` or `Errno::EAGAIN`) with `IO::WaitReadable` or `IO::WaitWritable`. If `IO::WaitWritable` is raised in your `NATS::IO::Socket#read`, the first rescue will still be the only one triggered because the original error that has been extended is still an `Errno::EWOULDBLOCK` or `Errno::EAGAIN`. The same situation occurs if a `IO::WaitReadable` is raised in `NATS::IO::Socket#write`.

RE: https://github.com/redis/redis-rb/pull/649
RE: https://github.com/ruby/ruby/blob/09ae127bade1d58705adfccb09a70403d8d909d5/io.c#L12346-L12349
RE: https://github.com/ruby/ruby/blob/09ae127bade1d58705adfccb09a70403d8d909d5/io.c#L12351-L12354

**Comment by wallyqs** [comment]
Thanks for the explanation, I will take a look and fix (btw official repo is now up at https://github.com/nats-io/pure-ruby-nats )

**Comment by djanowski** [comment]
You may be interested in redis-rb 3.3.3 which was just released.

**Comment by wallyqs** [comment]
Thanks for the advice here, now fixed it in master at https://github.com/nats-io/pure-ruby-nats/pull/17
